name: Build APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls
          unzip -o project-1-two-apks*.zip -d build
          ls build
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.7
      - run: cd build && gradle assembleAndroid5Debug assembleAndroid6Debug
      - uses: actions/upload-artifact@v4
        with:
          name: SinnersLite-apks
          path: build/app/build/outputs/apk/**/*.apk
